### PR TITLE
Reference elements by index rather than using .shift()

### PR DESCRIPTION
**Pull request by notmessenger**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* Reference elements by id rather than using `.shift()`

### CODE REVIEW

**Comment by juwara0** [comment]
👍

**Comment by notmessenger** [comment]
Resolves `TypeError: Cannot add/remove sealed array elements` error when running in an app that upgraded from Ember CLI 2.8.0 to 2.12.3

**Comment by juwara0** [comment]
👍

**Comment by juwara0** [comment]
👍

**Pull request merged**
